[package]
name = "projector"
version = "0.1.0"
authors = ["Timo Bryant <t.bryant@insiders-technologies.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
