[package]
name = "projector"
version = "0.1.0-pre"
authors = ["Timo Bryant <t.bryant@insiders-technologies.de>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
env_logger = "0.7.1"
log = "0.4.8"
toml = "0.5.6"
serde = "1.0.104"
snafu = "0.6.2"
